version: '2.1'

#file used for automated unitTest for pull requests
# see docker documentation for details 
# https://docs.docker.com/docker-hub/builds/automated-testing/#check-your-test-results
services:
  sut:
    build: .
    command: bash /root/tests/run_tests.sh
    depends_on:
      - mysql
      - postgres
      
  mysql:
      image: mysql:5.5
      ports:
        - 3308:3306
      environment:
          MYSQL_DATABASE: mysql_docker
          MYSQL_ROOT_PASSWORD: cAKd32Ga

  sql_server:
      image: microsoft/mssql-server-linux
      ports:
          - 1433:1433
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: sql_server_password
        secure_file_priv: ''

  postgres:
      image: postgres:9.6
      environment:
        POSTGRES_USER: dbu
        POSTGRES_PASSWORD: example
        POSTGRES_DB: dbutils
      ports:
        - 5420:5432